[package]
name = "shortest-path-server"
version = "0.1.0"
authors = ["Badi Abdul-Wahid <abdulwahidc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
assert2 = "0.2"
